language: d

sudo: required

addons:
  apt:
    packages:
      - libsdl1.2-dev

before_script:
  - wget https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
  - tar zxvf SDL2-2.0.5.tar.gz
  - cd SDL2-2.0.5
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR

script:
  - dub build
  - dub test
